version: "3"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app/front
    depends_on:
      - back

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./back:/app/back
      - /app/back/node_modules
    restart: always

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: staycation
      POSTGRES_DB: staycation
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: GMT
    volumes:
      - ./test-data.sql:/docker-entrypoint-initdb.d/init.sql
