version: "3"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app/front
    depends_on:
      - back
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - database
    volumes:
      - ./back:/app/back
      - /app/back/node_modules
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=staycation
      - POSTGRES_USER=staycation
      - POSTGRES_PASSWORD=password
      - TZ=GMT
    ports:
      - "5432:5432"
    volumes:
      - ./back/test-data.sql:/docker-entrypoint-initdb.d/init.sql
